# v0.9 -- 23.4.2023


# meta params
mutator_name: "ZedCustom.ZedCustomMut"
n_players: 5
difficulty: hoe
zed_multiplier: 2.00
modded: True
boss_wave_probability: 0.00
custom_zeds_ratio_policy: 'make_line_const_interp'
custom_zeds_ratio_policy_params: [1, 0.975, 20, 0.825]

# global (across all waves and zed types) params
spawn_at_once: 2
probability: 0.65
spawn_delay: 9.0
# number

# per-wave zeds specification
zeds_register:

  # STANDARD WAVES
  - num_wave: 1
    name: 'First Blood'
    spawn_delay: 6.0
    zeds:
      - zed: Prowler
        ratio: 1
        n_generators: 2 
      - zed: MrPelvis
        ratio: 0.4
      - zed: DarkCreep
        ratio: 0.1
      - zed: GreenBloat
        ratio: 0.4

  - num_wave: 2
    name: 'Creeping fear'
    spawn_delay: 7.5
    zeds:
      - zed: MagmaClot
        ratio: 3
        n_generators: 2
        spawn_at_once: 3
      - zed: Prowler
        ratio: 2
        n_generators: 2
      - zed: GreenClot
        ratio: 1
      - zed: DarkCreep
        ratio: 1
      - zed: MrPelvis
        ratio: 2
        n_generators: 2
      - zed: RedStalker
        ratio: 2
        n_generators: 2
      - zed: GreenBloat
        ratio: 1
      - zed: WhiteHusk
        ratio: 2
        n_generators: 2
      - zed: RedScrake
        number: 3
        spawn_at_once: 1

  - num_wave: 3
    name: 'Here comes the rockets'
    zeds:
      - zed: MagmaClot
        ratio: 4
        n_generators: 4
      - zed: Prowler
        ratio: 4
        n_generators: 4
      - zed: MrPelvis
        ratio: 2
        n_generators: 2
      - zed: GreenBloat
        ratio: 1.5
      - zed: WhiteHusk
        ratio: 3
        n_generators: 3
      - zed: RedFleshpound
        number: 3
        spawn_at_once: 1
      - zed: Revenant
        number: 3
        spawn_at_once: 1

  - num_wave: 4
    name: 'Hidding in the shadows of the fireworks'
    zeds:
      - zed: MagmaClot
        ratio: 2
        n_generators: 2
      - zed: Prowler
        ratio: 4
        n_generators: 4
      - zed: DarkCreep
        ratio: 2
        n_generators: 2
      - zed: MrPelvis
        ratio: 2
        n_generators: 2
      - zed: RedStalker
        ratio: 2
        n_generators: 2
      - zed: WhiteHusk
        ratio: 2
        n_generators: 2
      - zed: Sparky
        ratio: 2
        n_generators: 2
      - zed: RedScrake
        ratio: 0.5
      - zed: RedFleshpound
        number: 5
        spawn_at_once: 1

- num_wave: 4
    name: 'Who needs a boss anyway?'
    zeds:
      - zed: Prowler
        ratio: 4
        n_generators: 2
        spawn_at_once: 4
      - zed: Prowler
        ratio: 2
        n_generators: 2
      - zed: DarkCreep
        ratio: 2
        n_generators: 2
      - zed: MrPelvis
        ratio: 2
        n_generators: 2
      - zed: RedStalker
        ratio: 2
        n_generators: 2
      - zed: WhiteHusk
        ratio: 2
        n_generators: 2
      - zed: Sparky
        ratio: 2
        n_generators: 2
      - zed: RedFleshpound
        ratio: 1
      - zed: DoomBaron
        number: 10
      - zed: otis
        number: 1
        delay: 20.0
        spawn_at_once: 1