# v0.9 -- 23.4.2023


# meta params
mutator_name: "ZedCustom.ZedCustomMut"
n_players: 5
difficulty: hoe
zed_multiplier: 2.00
modded: True
boss_wave_probability: 0.00
custom_zeds_ratio_policy: 'make_line_const_interp'
custom_zeds_ratio_policy_params: [1, 0.75, 10, 0.9]

# global (across all waves and zed types) params
spawn_at_once: 2
probability: 0.65
spawn_delay: 9.0
# number

# per-wave zeds specification
zeds_register:

  # STANDARD WAVES
  - num_wave: 1
    name: 'First Blood'
    spawn_delay: 6.0
    probability: 0.8
    zeds:
      - zed: Prowler
        ratio: 1
        n_generators: 2 
      - zed: MrPelvis
        ratio: 0.2
      - zed: EliteCrawler
        ratio: 0.2
      - zed: GreenBloat
        ratio: 0.4

  - num_wave: 2
    name: 'Creeping fear'
    spawn_delay: 7.5
    probability: 0.75
    zeds:
      - zed: MagmaClot
        ratio: 3.0
        n_generators: 2
        spawn_at_once: 3
      - zed: Prowler
        ratio: 2.0
        n_generators: 2
      - zed: GreenClot
        ratio: 1.0
      - zed: DarkCreep
        ratio: 0.5
      - zed: MrPelvis
        ratio: 2.0
        n_generators: 2
      - zed: RedStalker
        ratio: 2.0
        n_generators: 2
      - zed: GreenBloat
        ratio: 1.0
      - zed: WhiteHusk
        ratio: 2.0
        n_generators: 2
      - zed: RedScrake
        number: 3
        spawn_at_once: 1

  - num_wave: 3
    name: 'Here comes the rockets'
    zeds:
      - zed: MagmaClot
        ratio: 4.0
        n_generators: 4
      - zed: Prowler
        ratio: 4.0
        n_generators: 4
      - zed: MrPelvis
        ratio: 2.0
        n_generators: 2
      - zed: GreenBloat
        ratio: 1.5
      - zed: WhiteHusk
        ratio: 3.0
        n_generators: 3
      - zed: RedFleshpound
        number: 3
        spawn_at_once: 1
      - zed: Revenant
        number: 3
        spawn_at_once: 1

  - num_wave: 4
    name: 'Hiding in the shadows of the fireworks'
    zeds:
      - zed: MagmaClot
        ratio: 2.0
        n_generators: 2
      - zed: Prowler
        ratio: 4.0
        n_generators: 4
      - zed: DarkCreep
        ratio: 2.0
        n_generators: 2
      - zed: MrPelvis
        ratio: 2.0
        n_generators: 2
      - zed: RedStalker
        ratio: 2.0
        n_generators: 2
      - zed: WhiteHusk
        ratio: 2.0
        n_generators: 2
      - zed: Sparky
        ratio: 2.0
        n_generators: 2
      - zed: RedScrake
        ratio: 0.5
      - zed: RedFleshpound
        number: 5
        spawn_at_once: 1

  - num_wave: 6
    name: 'Chainsaw massacre'
    zeds:
      - zed: MagmaClot
        ratio: 4.0
        n_generators: 2
        spawn_at_once: 4
      - zed: Prowler
        ratio: 2.0
        n_generators: 2
      - zed: MrPelvis
        ratio: 1.5
        n_generators: 2
      - zed: RedStalker
        ratio: 4.0
        n_generators: 4
      - zed: Sparky
        ratio: 3.0
        n_generators: 3
      - zed: BlueScrake
        ratio: 0.5
      - zed: RedScrake
        ratio: 1
      - zed: Scrake
        ratio: 2
        n_generators: 2
      - zed: Fleshpound
        number: 6

  - num_wave: 7
    name: 'Watch out for the rockets!'
    zeds:
      - zed: Prowler
        ratio: 2.0
        n_generators: 2
      - zed: GreenClot
        ratio: 5.0
        n_generators: 2
        spawn_at_once: 4
      - zed: DarkCreep
        ratio: 0.5
      - zed: EliteCrawler
        ratio: 2
      - zed: MrPelvis
        ratio: 1.5
        n_generators: 2
      - zed: GreenBloat
        ratio: 1.0
      - zed: WhiteHusk
        ratio: 3.0
        n_generators: 3
      - zed: Sparky
        ratio: 3.0
        n_generators: 3
      - zed: Fleshpound
        ratio: 1
        n_generators: 2
      - zed: Scrake
        ratio: 1
      - zed: Revenant
        ratio: 1

  - num_wave: 8
    name: 'Poundemonium'
    zeds:
      - zed: MagmaClot
        ratio: 4.0
        n_generators: 4
      - zed: Prowler
        ratio: 4.0
        n_generators: 2
        spawn_at_once: 4
      - zed: MrPelvis
        ratio: 1.0
      - zed: GreenBloat
        ratio: 2.0
        spawn_at_once: 4
      - zed: RedStalker
        ratio: 2.0
        n_generators: 2
      - zed: WhiteHusk
        ratio: 2
        n_generators: 3
      - zed: Quarterpound
        ratio: 2
      - zed: RedFleshpound
        ratio: 1
      - zed: Fleshpound
        ratio: 1
      - zed: DoomBaron
        number: 4

  - num_wave: 9
    name: 'Murder fiesta'
    zeds:
      - zed: MagmaClot
        ratio: 2.0
        n_generators: 2
      - zed: Prowler
        ratio: 5.0
        n_generators: 2
        spawn_at_once: 6
      - zed: GreenClot
        ratio: 2.0
        n_generators: 2
      - zed: DemonicClot
        ratio: 1.0
      - zed: MrPelvis
        ratio: 2.0
        n_generators: 2
      - zed: DarkCreep
        ratio: 1.0
      - zed: GreenBloat
        ratio: 1.0
        spawn_at_once: 4
      - zed: WhiteHusk
        ratio: 2
        n_generators: 2
      - zed: Sparky
        ratio: 1.0
      - zed: BlueScrake
        ratio: 1
        n_generators: 2
      - zed: RedScrake
        ratio: 1
        n_generators: 2
      - zed: RedFleshpound
        ratio: 1.5
        n_generators: 2
      - zed: Baron
        ratio: 0.5
      - zed: Revenant
        ratio: 1.0

  - num_wave: 11
    name: 'Lets start the grinder.'
    zeds:
      - zed: Prowler
        ratio: 18.0
        n_generators: 2
        spawn_at_once: 9
      - zed: HoneyBiscuit
        ratio: 3.0
        n_generators: 2
        spawn_at_once: 9
      - zed: DemonicClot
        ratio: 3.0
        n_generators: 2
        spawn_at_once: 9
      - zed: GreenBloat
        ratio: 2.0
        n_generators: 2
      - zed: DarkCreep
        ratio: 2.0
        n_generators: 2
      - zed: MrPelvis
        ratio: 2.0
        n_generators: 2
      - zed: RedStalker
        ratio: 12.0
        n_generators: 2
      - zed: BlueScrake
        ratio: 13.0
        n_generators: 2
      - zed: RedScrake
        ratio: 13.0
        n_generators: 2
      - zed: RedFleshpound
        ratio: 8.0
      - zed: DoomBaron
        number: 10
      - zed: HellfireHusk
        ratio: 8.0
        delay: 20.0
        spawn_at_once: 1
      - zed: Otis
        number: 1
        spawn_at_once: 1
        
  - num_wave: 12
    name: 'Getting hotter !'
    zeds:
      - zed: Prowler
        ratio: 14.0
        n_generators: 2
        spawn_at_once: 9
      - zed: HoneyBiscuit
        ratio: 3.0
        n_generators: 2
        spawn_at_once: 9
      - zed: DemonicClot
        ratio: 3.0
        n_generators: 2
        spawn_at_once: 9
      - zed: GreenBloat
        ratio: 2.0
        n_generators: 2
      - zed: DarkCreep
        ratio: 2.0
        n_generators: 2
      - zed: WhiteHusk
        ratio: 4.0
        n_generators: 2
      - zed: BlueScrake
        ratio: 13.0
        n_generators: 2
      - zed: RedScrake
        ratio: 15.0
        n_generators: 2
      - zed: RedFleshpound
        ratio: 7.0
      - zed: DoomBaron
        number: 20
      - zed: HellfireHusk
        ratio: 9.0
        delay: 20.0
        spawn_at_once: 1
      - zed: Otis
        number: 1
        spawn_at_once: 1

  - num_wave: 13
    name: 'Todo'
    zeds:
      - zed: Prowler
        ratio: 2.0
        n_generators: 2
      - zed: MagmaClot
        ratio: 4.0
        n_generators: 4
        spawn_at_once: 5
      - zed: DarkCreep
        ratio: 2.0
        n_generators: 4
        spawn_at_once: 2
      - zed: MrPelvis
        ratio: 1.0
        n_generators: 3
        spawn_at_once: 3
      - zed: RedStalker
        ratio: 3.0
        n_generators: 5
        spawn_at_once: 3
      - zed: GreenClot
        ratio: 1.0
        n_generators: 4
        spawn_at_once: 3
      - zed: GreenBloat
        ratio: 1.0
        n_generators: 2
        spawn_at_once: 2
      - zed: Sparky
        ratio: 1.0
        n_generators: 2
        spawn_at_once: 2
      - zed: BlueScrake
        ratio: 3.0
        n_generators: 2
        spawn_at_once: 3
      - zed: RedScrake
        ratio: 2.0
        n_generators: 2
        spawn_at_once: 3
      - zed: Otis
        number: 2
        spawn_at_once: 1
        delay: 30
      - zed: RedFleshpound
        number: 2
        n_generators: 3
        spawn_at_once: 1
      - zed: HellfireHusk
        number: 3
      - zed: BaronOfHell
        number: 1
        spawn_at_once: 1
      - zed: Revenant
        number: 5
        n_generators: 1
        spawn_at_once: 1

  - num_wave: 14
    name: 'Todo'
    zeds:
      - zed: Prowler
        ratio: 3.0
        n_generators: 2
      - zed: MagmaClot
        ratio: 4.0
        n_generators: 4
        spawn_at_once: 5
      - zed: WhiteHusk
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 5
      - zed: GreenClot
        ratio: 1.0
        n_generators: 4
        spawn_at_once: 3
      - zed: GreenBloat
        ratio: 1.5
        n_generators: 2
        spawn_at_once: 2
      - zed: WhiteHusk
        ratio: 1.0
        n_generators: 2
        spawn_at_once: 3
      - zed: Sparky
        ratio: 1.0
        n_generators: 2
        spawn_at_once: 2
      - zed: BlueScrake
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 1
      - zed: RedScrake
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 1
      - zed: Otis
        number: 3
        n_generators: 1
        spawn_at_once: 1
        delay: 20
      - zed: RedFleshpound
        number: 2
        n_generators: 3
        spawn_at_once: 1
      - zed: HellfireHusk
        number: 3
        n_generators: 2
        spawn_at_once: 4
      - zed: BaronOfHell
        number: 2
        n_generators: 3
        spawn_at_once: 1
      - zed: Revenant
        ratio: 1.0
        n_generators: 3
        spawn_at_once: 3

  - num_wave: 16
    name: 'Dawn of the end.'
    zeds:
      - zed: Prowler
        ratio: 18.0
        n_generators: 2
        spawn_at_once: 9
      - zed: GreenBloat
        ratio: 5.0
        n_generators: 2
      - zed: RedStalker
        ratio: 13.0
        n_generators: 2
      - zed: WhiteHusk
        ratio: 9.0
        n_generators: 2
      - zed: BlueScrake
        ratio: 13.0
        n_generators: 2
      - zed: RedScrake
        ratio: 13.0
        n_generators: 2
      - zed: RedFleshpound
        ratio: 8.0
      - zed: DoomBaron
        number: 30
      - zed: HellfireHusk
        ratio: 8.0
        delay: 20.0
        spawn_at_once: 1
      - zed: Otis
        number: 5
        n_generators: 2

  - num_wave: 17
    name: 'Listen to the heralds.'
    zeds:
      - zed: DarkCreep
        ratio: 6.0
        n_generators: 2
        spawn_at_once: 9
      - zed: GreenBloat
        ratio: 8.0
        n_generators: 2
      - zed: MrPelvis
        ratio: 13.0
        n_generators: 2
      - zed: RedStalker
        ratio: 16.0
        n_generators: 2
      - zed: WhiteHusk
        ratio: 11.0
        n_generators: 2
      - zed: Sparky
        ratio: 9.0
        n_generators: 2
      - zed: BlueScrake
        ratio: 13.0
        n_generators: 2
      - zed: RedScrake
        ratio: 13.0
        n_generators: 2
      - zed: RedFleshpound
        ratio: 8.0
      - zed: DoomBaron
        number: 40
      - zed: Otis
        number: 7
        n_generators: 2

  - num_wave: 18
    name: 'First sightings.'
    zeds:
      - zed: MagmaClot
        ratio: 12.0
        n_generators: 2
        spawn_at_once: 9
      - zed: Prowler
        ratio: 15.0
        n_generators: 2
        spawn_at_once: 9
      - zed: HoneyBiscuit
        ratio: 9.0
        n_generators: 2
        spawn_at_once: 9
      - zed: GreenBloat
        ratio: 5.0
        n_generators: 2
      - zed: DarkCreep
        ratio: 3.0
        n_generators: 2
      - zed: RedStalker
        ratio: 13.0
        n_generators: 2
      - zed: Mancubus
        number: 5
        n_generators: 2
      - zed: BlueHusk
        ratio: 4.0
        n_generators: 2
      - zed: WhiteHusk
        ratio: 9.0
        n_generators: 2
      - zed: BlueScrake
        ratio: 14.0
        n_generators: 2
      - zed: RedScrake
        ratio: 14.0
        n_generators: 2
      - zed: RedFleshpound
        ratio: 12.0
      - zed: DoomBaron
        number: 40
      - zed: HellfireHusk
        number: 10
        delay: 20.0
        spawn_at_once: 1
      - zed: Otis
        number: 7
        n_generators: 2

  - num_wave: 19
    name: 'Did you survive that? Good ! Now die.'
    zeds:
      - zed: MagmaClot
        ratio: 20.0
        n_generators: 2
        spawn_at_once: 9
      - zed: GreenBloat
        ratio: 6.0
        n_generators: 2
      - zed: DarkCreep
        ratio: 4.0
        n_generators: 2
      - zed: RedStalker
        ratio: 9.0
        n_generators: 2
      - zed: Mancubus
        number: 10
        n_generators: 2
      - zed: BlueHusk
        ratio: 4.0
        n_generators: 2
      - zed: WhiteHusk
        ratio: 9.0
        n_generators: 2
      - zed: Sparky
        ratio: 7.0
        n_generators: 2
      - zed: BlueScrake
        ratio: 14.0
        n_generators: 2
      - zed: RedScrake
        ratio: 14.0
        n_generators: 2
      - zed: DoomBaron
        number: 80
      - zed: HellfireHusk
        number: 10
        delay: 20.0
        spawn_at_once: 1
      - zed: Otis
        number: 10
        n_generators: 2

  - num_wave: 21
    name: 'We, who are about to die'
    zeds:
      - zed: Mancubus
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 5
      - zed: RedHusk
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 5
      - zed: WhiteHusk
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 5
      - zed: BlueHusk
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 5
      - zed: BlueScrake
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 5
      - zed: RedScrake
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 5
      - zed: Otis
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 5
      - zed: BaronOfHell
        ratio: 5.0
        n_generators: 2
        spawn_at_once: 5
      - zed: HellfireHusk
        ratio: 5.0
        n_generators: 2
        spawn_at_once: 5
      - zed: Revenant
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 5

  - num_wave: 36
    name: 'We, who are about to die'
    zeds:
      - zed: Mancubus
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 5
      - zed: RedHusk
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 5
      - zed: WhiteHusk
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 5
      - zed: BlueHusk
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 5
      - zed: BlueScrake
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 5
      - zed: RedScrake
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 5
      - zed: Otis
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 5
      - zed: BaronOfHell
        ratio: 5.0
        n_generators: 2
        spawn_at_once: 5
      - zed: HellfireHusk
        ratio: 5.0
        n_generators: 2
        spawn_at_once: 5
      - zed: Revenant
        ratio: 2.5
        n_generators: 2
        spawn_at_once: 5
